### ISSUE TITLE
Use recommended Redis separator (colon ":")

### ISSUE THREAD

**Issue by aabrodskiy** [andrewthetechie/pydantic-aioredis#192]
Thank you for maintaining this product!
It would be very convenient to use recommended and generally adopted Redis separator (colon) instead of the current "_%&_" separator.
This would make most Redis visualization tools automatically group items in the table and thus it would make debugging whole lot easier on large data sets.

This would be a small change in the return parameter of the below function:

    def __get_primary_key(cls, primary_key_value: Any):
        """
        Returns the primary key value concatenated to the table name for uniqueness
        """
        table_name = (
            cls.__name__.lower() if cls._table_name is None else cls._table_name
        )
        return f"{table_name}_%&_{primary_key_value}"

`return f"{table_name}:{primary_key_value}"`

<img width="612" alt="Screenshot 2022-07-04 at 18 51 09" src="https://user-images.githubusercontent.com/24899474/177200707-0d3e98c6-968a-4e70-9daf-12f13c768d38.png">
"

**Comment by andrewthetechie** [comment]
Thanks for the feedback! This sounds like a valuable change.

I'd happily accept a PR making this change. I'll see if I get some free time to do it myself in the future

**Comment by andrewthetechie** [comment]
No problem.

If want to give it a try, check out https://docs.github.com/en/get-started/quickstart/contributing-to-projects as a guide to get started on forking and PRing on Github. Here is pydantic-aioredis's contributing guide https://github.com/andrewthetechie/pydantic-aioredis/blob/main/CONTRIBUTING.rst which has some documentation that might be helpful too

The tl;dr on the process would be:

* force this repo
* Make the changes to your fork and commit them. pydantic-aioredis uses Conventional Commits for commit message https://www.conventionalcommits.org/en/v1.0.0/
* Update tests and any documentation
* Make a PR back to this repo

**Comment by andrewthetechie** [comment]
https://github.com/andrewthetechie/pydantic-aioredis/pull/269

This feature will be included in the 1.0.0 release once that PR is merged. I'm shooting to have it merged soon.

**Comment by andrewthetechie** [comment]
This feature is included in https://github.com/andrewthetechie/pydantic-aioredis/releases/tag/v1.0.0 which is available in pypi now
