### ISSUE TITLE
Question: How to configure prefixes for the created Redis keys?

### ISSUE THREAD

**Issue by david-wahlstedt** [andrewthetechie/pydantic-aioredis#277]
**Is your feature request related to a problem? Please describe.**
In order to separate unrelated concerns in the Redis database, it is customary to use colon separated key prefixes. I can't see this option available in pydantic-aioredis. Would it be possible/easy to add?

Ideally, I would like to have the possibility to specify that all the Redis entries created by my application has some "foo:" as a key prefix.

I found a possiblility to add a prefix in the constructor of a PydanticAioredisCRUDRouter, but I guess this is not meant to use just in order to configure one's Redis key prefixes?

I tried to find an email address to send my question to, but I only found a "no-reply" address, so I filed this issue instead. Sorry if I'm not posing the question the right way.

BR,
David

**Comment by andrewthetechie** [comment]
Hi David, it's totally fine to file an issue - no need to send emails. I monitor issues on the repo and do my best to respond in at most a day or two.

This issue sounds similar to https://github.com/andrewthetechie/pydantic-aioredis/issues/192. At this time, this is not a feature but it sounds like a reasonable request. I'd be happy to accept a PR with this change.

**Comment by andrewthetechie** [comment]
@david-wahlstedt I'm working on a feature that would support your use case in https://github.com/andrewthetechie/pydantic-aioredis/pull/278

**Comment by david-wahlstedt** [comment]
> @david-wahlstedt I'm working on a feature that would support your use case in #278

Thanks a lot :-)

**Comment by andrewthetechie** [comment]
https://github.com/andrewthetechie/pydantic-aioredis/pull/269

A feature that allows you to set a prefix will be included in the 1.0.0 release once that PR is merged. I'm shooting to have it merged in the next 7 days

**Comment by andrewthetechie** [comment]
This feature is included in https://github.com/andrewthetechie/pydantic-aioredis/releases/tag/v1.0.0 which is available in pypi now

**Comment by david-wahlstedt** [comment]
> This feature is included in https://github.com/andrewthetechie/pydantic-aioredis/releases/tag/v1.0.0 which is available in pypi now

Thanks! Awesome!!!
