### ISSUE TITLE
Example request: An example with custom serialization/desrialization

### ISSUE THREAD

**Issue by andrewthetechie** [andrewthetechie/pydantic-aioredis#289]
**Describe the solution you'd like**
A new example that shows a custom serializer/deserializer based on the documentation https://pydantic-aioredis.readthedocs.io/en/latest/serialization.html

This example should show overriding json_default and serialize_partially/deserialize_partially.

**Comment by devbazregari** [comment]
bro would you please explain a little bit more about what you want ?

**Comment by andrewthetechie** [comment]
Hello @devbazregari, 

This would be an example in the examples/ directory, preferably in a subdirectory like `serialization` that demonstrates how to customize serialization and deserialization when using pydantic-aioredis.

**Comment by devbazregari** [comment]
in fact, do you want me to show an example of serializing and deserializing in pydantic aioredis?

**Comment by andrewthetechie** [comment]
@devbazregari feel free to make a PR, but I may not accept it if the example does not match the quality of our other examples. This issue is a goal as part of the 1.0 release of this library to make sure that things are well documented and have examples for users to follow.

**Comment by andrewthetechie** [comment]
Ok, the goal is to release 1.0 this week

**Comment by devbazregari** [comment]
bro in overriding json_default and serialize_partially/deserialize_partially do you want me to implement the logic or just show users how to override ?! I'm asking this stupid question :)  because I read your code and see you implemented the logic.
