### ISSUE TITLE
Storing Lists and other complex data types failing in 1.2.0

### ISSUE THREAD

**Issue by andrewthetechie** [andrewthetechie/pydantic-aioredis#408]
**Describe the bug**
Originally reported by [david-wahlstedt](https://github.com/david-wahlstedt)

**To Reproduce**
In the latest version (1.2.0) of pydantic-aioredis, I can't store lists at all. The following fails:

```
class DataTypeTest(Model):
    _primary_key_field: str = "key"

    key: str
    value: Optional[List[int]]

store.register_model(DataTypeTest)

def test_list_storage():
    key = "test_list_storage"
    instance = DataTypeTest(
        key=key,
        value=[1,2,3],
    )
    sync(instance.save()) # just test it doesn't crash, ok in 1.0.0, but not in 1.2.0
```

This works fine in 1.0.0, so something must have broken?

**Expected behavior**
Lists and other complex data types should be stored as json strings

**Comment by andrewthetechie** [comment]
I yanked the 1.2.0 release after confirming this problem

**Comment by andrewthetechie** [comment]
Hi @david-wahlstedt,

Please give the 1.2.1 release a try. I fixed the issue with complex types (list, dict, tuple, etc)

**Comment by david-wahlstedt** [comment]
> Hi @david-wahlstedt,
> 
> Please give the 1.2.1 release a try. I fixed the issue with complex types (list, dict, tuple, etc)

Thanks for the fix! I have tested it and it seems to work fine with my tests, also with generics in the types.

**Comment by andrewthetechie** [comment]
Awesome to hear, I'll close this and the issue about generics
