### ISSUE TITLE
README example has typo

### ISSUE THREAD

**Issue by kraczak** [andrewthetechie/pydantic-aioredis#545]
If I understand it correctly,

```python
assert this_book_from_redis[0].author == date(year=1851, month=10, day=18)
```
should be changed to 
```python 
assert this_book_from_redis[0].published_on == date(year=1851, month=10, day=18)
```

**Comment by andrewthetechie** [comment]
Good catch, fixed in https://github.com/andrewthetechie/pydantic-aioredis/commit/992c4a12ce83df793c13c9f266a704adb67ab7d4.

Thanks!

https://github.com/all-contributors please add @kraczak for doc.

**Comment by andrewthetechie** [comment]
@all-contributors please add @kraczak for doc.
